# примеры API-запросов

@baseUrl = http://localhost:8000

# регистрация клиента
POST {{baseUrl}}/profile/
Content-Type: application/json

{
  "first_name": "Andrey",
  "last_name": "Minin",
  "username": "Mininttaasd",
  "email": "Mininttaasd@gmail.com",
  "company": "MininCom",
  "position": "Director"
}

###

# аутентификация клиента
POST {{baseUrl}}/login/
Content-Type: application/json

{
  "email": "Mininttaasd@gmail.com",
  "password": "GAd,KXF>C&"
}

###

# проверка аутентификации клиента
GET {{baseUrl}}/login/
Cookie: 
###

# выход из аутентификации
GET {{baseUrl}}/logout/
Content-Type: application/json

###

# проверка профиля пользователя
GET {{baseUrl}}/profile/
Content-Type: application/json

{
  "email": "Minine@gmail.com"
}

###

# изменения данных профиля
POST {{baseUrl}}/profile/
Content-Type: application/json

{
  "first_name": "AndreyAAA",
  "last_name": "MininAAA",
  "email": "Minine@gmail.com"
}

###

# регистрация магазина
POST {{baseUrl}}/profile/shop/
Content-Type: application/json

{
  "first_name": "Andrey",
  "last_name": "Minin",
  "username": "Minin1HHH",
  "email": "MininHHH@gmail.com",
  "company": "MininCom",
  "position": "Director",
  "type": "shop"
}

###