# примеры API-запросов

@baseUrl = http://localhost:8000

# регистрация клиента
POST {{baseUrl}}/profile/
Content-Type: application/json

{
  "first_name": "Andrey",
  "last_name": "Minin",
  "username": "Mininff5f4xxffj",
  "email": "Mininfxfg4x5@gmail.com",
  "company": "MininCom",
  "position": "Director"
}

###

# подтверждение почты
POST {{baseUrl}}/profile/email/
Content-Type: application/json

{
  "email": "Mininfxfg4x5@gmail.com",
  "token": "ddb49849a3e101fb4a918c49d67f88549e8648"
}

###

# аутентификация клиента
POST {{baseUrl}}/login/
Content-Type: application/json

{
  "email": "Mininfxfg4x5@gmail.com",
  "password": "zZ~cGp9?5<"
}

###

# проверка аутентификации клиента
GET {{baseUrl}}/login/
Authorization: Token ae6667bf146d9a05802602662990c0ffbc15fffc
###

# выход из аутентификации
GET {{baseUrl}}/logout/
Authorization: Token 44e2160a92a88cbb2fc08217569e5ed667abd5ce

###

# проверка профиля пользователя
GET {{baseUrl}}/profile/
Content-Type: application/json

{
  "email": "Minine@gmail.com"
}

###

# изменения данных профиля
POST {{baseUrl}}/profile/
Content-Type: application/json

{
  "first_name": "AndreyAAA",
  "last_name": "MininAAA",
  "email": "Minine@gmail.com"
}

###

# регистрация магазина
POST {{baseUrl}}/profile/shop/
Content-Type: application/json

{
  "first_name": "Andrey",
  "last_name": "Minin",
  "username": "Minin1HHH",
  "email": "MininHHH@gmail.com",
  "company": "MininCom",
  "position": "Director",
  "type": "shop"
}

###

{"items": [{"product_info": 25, "quantity": 13}, {"product_info": 26, "quantity": 12,}]}