# Generated by Django 4.2.5 on 2023-10-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_client_email_alter_contact_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="shops",
            new_name="shop",
        ),
        migrations.AddField(
            model_name="category",
            name="id_category",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="Номер категории"
            ),
        ),
    ]
